/**
 * About: load some initial data to the DB collection, rooms
 * Note: only need this for collection rooms; whereas
 * the other two (useres and messages) can be generated by using this live Q&A app
 */

const roomController = require("./Room");

const newRoom = {
  roomName: "Watermelon",
  hostName: "Watermelon",
  topic: "Watermelon juice. Yummy!",
  icon: "./assets/watermelon.png"
};

roomController.addRooms(newRoom, (err, data) => {
  if (err) {
    console.log("Error, in loading new data to DB rooms.");
  } else {
    console.log("Success! Added a new room, " + newRoom.roomName + ".");
  }
});
